package Modelos;
// Generated 23/09/2015 10:10:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bibliotecas generated by hbm2java
 */
public class Bibliotecas  implements java.io.Serializable {


     private Integer idBiblioteca;
     private String nombre;
     private String direccion;
     private String ciudad;
     private String pais;
     private Set usuarioses = new HashSet(0);
     private Set libroses = new HashSet(0);

    public Bibliotecas() {
    }

    public Bibliotecas(String nombre, String direccion, String ciudad, String pais, Set usuarioses, Set libroses) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.pais = pais;
       this.usuarioses = usuarioses;
       this.libroses = libroses;
    }
   
    public Integer getIdBiblioteca() {
        return this.idBiblioteca;
    }
    
    public void setIdBiblioteca(Integer idBiblioteca) {
        this.idBiblioteca = idBiblioteca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set libroses) {
        this.libroses = libroses;
    }




}


