package Modelos;
// Generated 23/09/2015 10:10:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer idLibro;
     private Bibliotecas bibliotecas;
     private String isbn;
     private String titulo;
     private Set prestamoses = new HashSet(0);

    public Libros() {
    }

	
    public Libros(Bibliotecas bibliotecas, String isbn, String titulo) {
        this.bibliotecas = bibliotecas;
        this.isbn = isbn;
        this.titulo = titulo;
    }
    public Libros(Bibliotecas bibliotecas, String isbn, String titulo, Set prestamoses) {
       this.bibliotecas = bibliotecas;
       this.isbn = isbn;
       this.titulo = titulo;
       this.prestamoses = prestamoses;
    }
   
    public Integer getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(Integer idLibro) {
        this.idLibro = idLibro;
    }
    public Bibliotecas getBibliotecas() {
        return this.bibliotecas;
    }
    
    public void setBibliotecas(Bibliotecas bibliotecas) {
        this.bibliotecas = bibliotecas;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set prestamoses) {
        this.prestamoses = prestamoses;
    }




}


