package Modelos;
// Generated 23/09/2015 10:10:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Prestamos generated by hbm2java
 */
public class Prestamos  implements java.io.Serializable {


     private Integer idPrestamo;
     private Libros libros;
     private Usuarios usuarios;
     private Date fechaPrestamo;
     private Date fechaEntrega;

    public Prestamos() {
    }

	
    public Prestamos(Libros libros, Usuarios usuarios, Date fechaEntrega) {
        this.libros = libros;
        this.usuarios = usuarios;
        this.fechaEntrega = fechaEntrega;
    }
    public Prestamos(Libros libros, Usuarios usuarios, Date fechaPrestamo, Date fechaEntrega) {
       this.libros = libros;
       this.usuarios = usuarios;
       this.fechaPrestamo = fechaPrestamo;
       this.fechaEntrega = fechaEntrega;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Libros getLibros() {
        return this.libros;
    }
    
    public void setLibros(Libros libros) {
        this.libros = libros;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }
    
    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }




}


