package Modelos;
// Generated 23/09/2015 10:10:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private Bibliotecas bibliotecas;
     private String nombres;
     private String apellidos;
     private String documento;
     private String username;
     private String password;
     private String tipo;
     private Set prestamoses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(Bibliotecas bibliotecas, String nombres, String apellidos, String documento, String username, String password, String tipo) {
        this.bibliotecas = bibliotecas;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.documento = documento;
        this.username = username;
        this.password = password;
        this.tipo = tipo;
    }
    public Usuarios(Bibliotecas bibliotecas, String nombres, String apellidos, String documento, String username, String password, String tipo, Set prestamoses) {
       this.bibliotecas = bibliotecas;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.documento = documento;
       this.username = username;
       this.password = password;
       this.tipo = tipo;
       this.prestamoses = prestamoses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Bibliotecas getBibliotecas() {
        return this.bibliotecas;
    }
    
    public void setBibliotecas(Bibliotecas bibliotecas) {
        this.bibliotecas = bibliotecas;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set prestamoses) {
        this.prestamoses = prestamoses;
    }




}


